CREATE SEQUENCE COMPRAOQ.SEQ_LISTA
START WITH 1 INCREMENT BY 1;

CREATE TABLE COMPRAOQ.LISTA(
    ID        BIGINT       DEFAULT NEXTVAL('COMPRAOQ.SEQ_LISTA') ,
    DESCRICAO VARCHAR(250) ,
    LOCAL	  SMALLINT	   ,
    
    CONSTRAINT PK$LISTA PRIMARY KEY(ID)
);