CREATE SEQUENCE COMPRAOQ.SEQ_ITEM
START WITH 1 INCREMENT BY 1;

CREATE TABLE COMPRAOQ.ITEM(
    ID        BIGINT       DEFAULT NEXTVAL('COMPRAOQ.SEQ_ITEM') ,
    DESCRICAO VARCHAR(250) ,
    LOCAL	  SMALLINT	   ,
    
    CONSTRAINT PK$ITEM PRIMARY KEY(ID)
);